apps/AdminsApp/urls.py
from django.urls import path
from .views import *

app_name = 'admin'

urlpatterns = [
    path('', home, name='home'),

    # URLs para empleados
    path('puestos/', puestos, name='puestos'),
    path('empleados/<str:tipo>', empleados, name='empleados'),
    path('actualizar_empleado/<int:pk>', actualizar_empleado, name='actualizar_empleado'),
    path('eliminar_empleado/', eliminar_empleado, name='eliminar_empleado'),

    # URLs para ver los pedidos
    path('pedidos', pedidos, name='pedidos'),
    path('actualizar_pedidos/<slug:slug>', pedidos, name='actualizar_pedidos'),

    # URLs para agregar categorias de alimentos
    path('categorias', categorias, name='categorias'),
    path('actualizar_categorias/<slug:slug>', categorias, name='actualizar_categorias'),

    # URLs para ver las cajas
    path('cajas', cajas, name='cajas'),
    path('actualizar_cajas/<slug:slug>', actualizarCajas, name='actualizar_cajas'),
    path('eliminar_cajas/', eliminar_Cajas, name='eliminar_cajas'),

    # URLs para ver las cajas
    path('tipo_operacion', tipo_operacion, name='tipo_operacion'),
    path('actualizar_tipo_operacion/<slug:slug>', actualizarTipo_operacion, name='actualizar_tipo_operacion'),
    path('eliminar_tipo_operacion/', eliminar_Tipo_operacion, name='eliminar_tipo_operacion'),

    # URLs para ver las denominaciones
    path('denominacion', denominacion, name='denominacion'),
    path('actualizar_denominacion/<slug:slug>', actualizarDenominacion, name='actualizar_denominacion'),
    path('eliminar_denominacion/', eliminar_Denominacion, name='eliminar_denominacion'),

    # URLs para ver el uso de cajas
    path('registro_cajas', registro_cajas, name='registro_cajas'),
    path('actualizar_registro_cajas/<slug:slug>', actualizarRegistro_cajas, name='actualizar_registro_cajas'),
    path('eliminar_registro_cajas', eliminar_Registro_cajas, name='eliminar_registro_cajas'),

    # URLs para ver el manejo de los Alimentos
    path('alimentos', alimentos, name='alimentos'),
    path('actualizar_alimentos/<slug:slug>', actualizarAlimentos, name='actualizar_alimentos'),
    path('eliminar_alimentos/', eliminar_Alimentos, name='eliminar_alimentos'),

    # URLs para ver el manejo de los Alimentos
    path('combos', combos, name='combos'),
    path('actualizar_combos/<slug:slug>', actualizarCombos, name='actualizar_combos'),
    path('eliminar_combos/', eliminar_Combos, name='eliminar_combos'),

    # URLs para ver el manejo de los Alimentos
    path('productos', productos, name='productos'),
    path('actualizar_productos/<slug:slug>', actualizarProductos, name='actualizar_productos'),
    path('eliminar_productos/', eliminar_Producto, name='eliminar_productos'),

    # URLs para ver el manejo de las promociones
    path('promociones', promociones, name='promos'),
    path('actualizar_promociones/<slug:slug>', actualizarPromociones, name='actualizar_promos'),
    path('eliminar_promociones/', eliminar_Promocion, name='eliminar_promos'),

    # URLs para ver el manejo de las promociones
    path('proveedores', proveedores, name='proveedores'),
    path('actualizar_proveedores/<slug:slug>', actualizarProveedores, name='actualizar_proveedores'),
    path('eliminar_proveedores/', eliminar_Proveedores, name='eliminar_proveedores'),

]

punto_de_venta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admino/', admin.site.urls),
    path('', include('apps.MainApp.urls')),
    path('cajeros/', include('apps.CajerosApp.urls')),
    path('meseros/', include('apps.MeserosApp.urls')),
    path('admin/', include('apps.AdminsApp.urls')),
]

apps/Producto/models.py
import uuid

from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify

from ..EmpleadosApp.models import User


class TBL_CATEGORIA_ALIMENTOS(models.Model):
    nombre = models.CharField('Nombre de la categoria', max_length=255, default='')
    tipo = models.CharField('Tipo de la categoria', blank=True, max_length=255, default='')
    active = models.BooleanField('Activo', default=True)
    slug = models.CharField('Nombre de la categoria', max_length=255, default='')

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

    def __str__(self):
        return self.nombre


def set_slug_CATEGORIA_ALIMENTOS(sender, instance, *args, **kwargs):
    slug = slugify(
        '{}-{}'.format(instance.slug, str(uuid.uuid4())[:8])
    )
    instance.slug = slug


pre_save.connect(set_slug_CATEGORIA_ALIMENTOS, sender=TBL_CATEGORIA_ALIMENTOS)


class Cat_Proveedores(models.Model):
    razon_social = models.CharField('Razon social', max_length=255, default='')
    telefono = models.CharField('Telefono', max_length=10, default='')
    cp = models.CharField('Codigo postal', max_length=5, default='')
    calle = models.CharField('Calle', max_length=255, default='')
    no_ext = models.CharField('Numero exterior', max_length=255, default='')
    no_int = models.CharField('Numero interior', max_length=255, default='')
    correo = models.EmailField('Correo electronico', max_length=255, default='')
    colonia = models.CharField('Colonia', max_length=255, default='')
    estado = models.CharField('Estado', max_length=255, default='')
    pais = models.CharField('Pais', max_length=255, default='')
    active = models.BooleanField('Activo', default=True)
    slug = models.CharField(max_length=100, null=False, blank=False, unique=True, default='')

    class Meta:
        verbose_name = 'Proveedor'
        verbose_name_plural = 'Proveedores'

    def __str__(self):
        return self.razon_social


def set_slug_Proveedores(sender, instance, *args, **kwargs):
    slug = slugify(
        '{}-{}'.format(instance.razon_social, str(uuid.uuid4())[:8])
    )
    instance.slug = slug


pre_save.connect(set_slug_Proveedores, sender=Cat_Proveedores)


class CAT_Producto(models.Model):
    nombre = models.CharField('Nombre', max_length=255, default='')
    descripcion = models.CharField('Descripcion', max_length=255, default='')
    id_categoria = models.ForeignKey(TBL_CATEGORIA_ALIMENTOS, on_delete=models.CASCADE)
    activo = models.BooleanField('Activo', default=True)
    precio = models.DecimalField(max_digits=20, decimal_places=2)
    cantidad = models.IntegerField('Cantidad', blank=True, null=True)
    active = models.BooleanField('Activo', default=True)
    slug = models.CharField(max_length=100, null=False, blank=False, unique=True, default='')

    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'

    def __str__(self):
        return self.nombre


def set_slug_Producto(sender, instance, *args, **kwargs):
    slug = slugify(
        '{}-{}'.format(instance.nombre, str(uuid.uuid4())[:8])
    )
    instance.slug = slug


pre_save.connect(set_slug_Producto, sender=CAT_Producto)


class TBL_Inventario(models.Model):
    id_usuario = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    id_numero_inventario = models.IntegerField('Numero Inventario',  null=True)
    fecha = models.DateTimeField('Fecha', auto_now=True)
    id_producto = models.ForeignKey(CAT_Producto, on_delete=models.CASCADE, null=True)
    cantidad = models.IntegerField('Cantidad')
    id_estatus = models.BooleanField('Estado', default=False)
    precio_paquete = models.DecimalField('Precio del paquete', decimal_places=2, max_digits=99999)
    precio_unitario = models.DecimalField('Precio unitario', decimal_places=2, max_digits=99999)
    id_proveedor = models.ForeignKey(Cat_Proveedores, on_delete=models.CASCADE)
    active = models.BooleanField('Activo', default=True)
    slug = models.CharField(max_length=100, null=False, blank=False, unique=True, default='')

    class Meta:
        verbose_name = 'Inventario'
        verbose_name_plural = 'Inventarios'

    def __str__(self):
        return self.cantidad


def set_slug_Inventario(sender, instance, *args, **kwargs):
    slug = slugify(
        '{}-{}'.format('Inventario', str(uuid.uuid4())[:8])
    )
    instance.slug = slug


pre_save.connect(set_slug_Inventario, sender=TBL_Inventario)


class TBL_COMBOS(models.Model):
    nombre = models.CharField('Nombre', max_length=255, default='')
    descripcion = models.CharField('Descripcion', max_length=255, default='')
    precio = models.DecimalField('Precio', decimal_places=2, max_digits=99999)
    id_estatus = models.BooleanField('Estado', default=True)
    id_producto = models.ManyToManyField(CAT_Producto, verbose_name='Producto')
    active = models.BooleanField('Activo', default=True)
    slug = models.CharField(max_length=100, null=False, blank=False, unique=True, default='')

    class Meta:
        verbose_name = 'Combo'
        verbose_name_plural = 'Combos'

    def __str__(self):
        return self.nombre


def set_slug_COMBOS(sender, instance, *args, **kwargs):
    slug = slugify(
        '{}-{}'.format(instance.nombre, str(uuid.uuid4())[:8])
    )
    instance.slug = slug


pre_save.connect(set_slug_COMBOS, sender=TBL_COMBOS)


class TBL_Promociones(models.Model):
    nombre = models.CharField('Nombre', max_length=255, default='')
    descripcion = models.CharField('Descripcion', max_length=255, default='')
    porcentaje = models.IntegerField('Porcentaje')
    id_estatus = models.BooleanField('Estado', default=True)
    active = models.BooleanField('Activo', default=True)
    slug = models.CharField(max_length=100, null=False, blank=False, unique=True, default='')

    class Meta:
        verbose_name = 'Promocion'
        verbose_name_plural = 'Promociones'

    def __str__(self):
        return self.nombre


def set_slug_Promociones(sender, instance, *args, **kwargs):
    slug = slugify(
        '{}-{}'.format(instance.nombre, str(uuid.uuid4())[:8])
    )
    instance.slug = slug


pre_save.connect(set_slug_Promociones, sender=TBL_Promociones)


class CAT_ALIMENTOS(models.Model):
    nombre = models.CharField('Nombre', max_length=255, default='')
    descripcion = models.CharField('Descripcion', max_length=255, default='')
    id_categoria = models.ForeignKey(TBL_CATEGORIA_ALIMENTOS, on_delete=models.CASCADE)
    precio = models.DecimalField('Precio', decimal_places=2, max_digits=99999)
    active = models.BooleanField('Activo', default=True)
    slug = models.CharField(max_length=100, null=False, blank=False, unique=True, default='')

    class Meta:
        verbose_name = 'Alimento'
        verbose_name_plural = 'Alimentos'

    def __str__(self):
        return self.nombre


def set_slug_ALIMENTOS(sender, instance, *args, **kwargs):
    slug = slugify(
        '{}-{}'.format(instance.nombre, str(uuid.uuid4())[:8])
    )
    instance.slug = slug


pre_save.connect(set_slug_ALIMENTOS, sender=CAT_ALIMENTOS)

apps/Productos/models.py
from decimal import Decimal

from django.db import models


class Productos(models.Model):
    nombre = models.CharField('Nombre', max_length=255, default='')
    descripcion = models.CharField('Descripcion', max_length=255, default='')
    categoria = models.CharField('Categoria', max_length=255, default='')
    activo = models.BooleanField('Activo', default=True)
    precio = models.DecimalField(max_digits=20, decimal_places=2)

apps/Producto/forms.py
from django import forms
from .models import CAT_Producto, CAT_ALIMENTOS, TBL_COMBOS, TBL_Promociones, Cat_Proveedores


class alimentosForm(forms.ModelForm):
    class Meta:
        model = CAT_ALIMENTOS

        fields = [
            'nombre', 'id_categoria', 'descripcion', 'precio'
        ]


class combosForm(forms.ModelForm):
    class Meta:
        model = TBL_COMBOS

        fields = [
            'nombre', 'descripcion', 'precio', 'id_estatus', 'id_producto'
        ]

        widgets = {
            'id_producto': forms.SelectMultiple(
                attrs={
                    'class': 'selectpicker'
                }
            ),
        }


class promosForm(forms.ModelForm):
    class Meta:
        model = TBL_Promociones

        fields = [
            'nombre', 'descripcion', 'porcentaje', 'id_estatus'
        ]


class ProductosForm(forms.ModelForm):
    class Meta:
        model = CAT_Producto
        fields = [
            'nombre', 'descripcion', 'id_categoria', 'activo', 'precio', 'cantidad'
        ]

        widgets = {
            'nombre': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingresa el nombre'
                }
            ),
            'descripcion': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingresa la descripcion'
                }
            ),
            'categoria': forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'Ingresa el nombre'
                }
            ),

        }


class proveedoresForm(forms.ModelForm):
    class Meta:
        model = Cat_Proveedores

        fields = [
            'razon_social', 'telefono', 'cp', 'calle', 'no_ext', 'no_int', 'correo', 'colonia', 'estado', 'pais'
        ]

apps/Productos/forms.py
from django import forms
from apps.Productos.models import Productos


class menuForm(forms.ModelForm):
    class Meta:
        model = Productos
        fields = [
            'nombre', 'descripcion', 'categoria', 'precio', 'activo'
        ]

        widgets = {
            'nombre': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingresa el nombre'
                }
            ),
            'descripcion': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingresa el nombre'
                }
            ),
            'categoria': forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'Ingresa el nombre'
                }
            ),
            'precio': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': '0.00',
                    'type': 'number',
                    'min': 1,
                    'step': '0.01'
                }
            )

        }

apps/Producto/views.py
from django.shortcuts import render

# Create your views here.

templates/Admins/Alimentos/productos/actualizarProductos.html
{% extends 'Admins/navbar.html' %}

    {% block title %}Actualizar{% endblock %}

{% block body %}

    <div class="container">
    <div class="col-md-6">
        <form method="post">
            {% csrf_token %}

            {{ form }}

            <div class="row justify-content-md-center mt-5">
                <button type="submit" class="btn btn-success">Actualizar</button>
            </div>
        </form>
    </div>
    </div>

{% endblock %}

templates/Admins/Alimentos/productos/productos.html
{% extends 'Admins/navbar.html' %}
{% load static %}


{% block title %} Productos {% endblock %}

{% block css %}
    <style>
        #btnsubmit {
            background: url(../../../../static/recursos/img/trash.png) no-repeat;
            width: 28px;
            height: 28px;
            border: none;
        }
    </style>
{% endblock %}

{% block body %}

    <div class="container">


        <div class="row justify-content-center mt-5">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#agregarProductoModal">
                Agregar Producto
            </button>
        </div>

    <div class="row justify-content-md-center">
            <div class=" mt-4 mb-5">
                {% for message in messages %}
                    {% if message.tags == "error" %}
                        <p class="bg-danger" style="font-size: 24px; color: white;">{{ message }}</p>
                    {% else %}
                        <p class="bg-success" style="font-size: 24px; color: white;">{{ message }}</p>
                    {% endif %}

                {% endfor %}
            </div>
        </div>


        {% if query %}

            <div class="row mt-5">
                <table class="table">
                    <thead class="thead-light">
                    <tr>
                        <th scope="col">Nombre</th>
                        <th scope="col">Categoria</th>
                        <th scope="col">Descripcion</th>
                        <th scope="col">Precio</th>
                        <th scope="col">Cantidad</th>
                        <th scope="col">Opciones</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for i in query %}
                        <tr>
                            <td>{{ i.nombre }}</td>
                            <td>{{ i.categoria }}</td>
                            <td>{{ i.descripcion }}</td>
                            <td>{{ i.precio }}</td>
                            <td>{{ i.cantidad }}</td>

                            <td>
                                <div class="row">
                                    <div class="col">
                                        <a href="{% url 'admin:actualizar_productos' i.slug %}"> <img
                                                src="{% static 'recursos/img/actualizar.png' %}"></a>
                                    </div>

                                    <div class="col">
                                        <form method="post" action="{% url 'admin:eliminar_productos' %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="slug" value="{{ i.slug }}">
                                        <button type="submit" id="btnsubmit"></button>
                                    </form>

                                    </div>
                                </div>
                            </td>

                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

        {% else %}

            <div class="row justify-content-md-center">
                <div class="mt-4">
                    <h3>No hay combos</h3>
                </div>
            </div>

        {% endif %}

    </div>



<!-- Modal -->
<div class="modal fade" id="agregarProductoModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="post">
        {% csrf_token %}

            {{ form.as_p }}

            <button type="submit" class="btn btn-success mt-4">Guardar</button>
        </form>
      </div>

    </div>
  </div>
</div>
    {% block script %}

        <script>
            document.getElementById('btnForm').addEventListener('click', function () {
                document.getElementById('form').submit()
            })
        </script>
        <script src="{% static 'js/empleados/empleados.js' %}"></script>



    {% endblock %}

{% endblock %}