apps/AdminsApp/urls.py
from django.urls import path
from .views import *

app_name = 'admin'

urlpatterns = [
    path('', home, name='home'),

    # URLs para empleados
    path('puestos/', puestos, name='puestos'),
    path('empleados/<str:tipo>', empleados, name='empleados'),
    path('actualizar_empleado/<int:pk>', actualizar_empleado, name='actualizar_empleado'),
    path('eliminar_empleado/', eliminar_empleado, name='eliminar_empleado'),

    # URLs para ver los pedidos
    path('pedidos', pedidos, name='pedidos'),
    path('actualizar_pedidos/<slug:slug>', pedidos, name='actualizar_pedidos'),

    # URLs para agregar categorias de alimentos
    path('categorias', categorias, name='categorias'),
    path('actualizar_categorias/<slug:slug>', categorias, name='actualizar_categorias'),

    # URLs para ver las cajas
    path('cajas', cajas, name='cajas'),
    path('actualizar_cajas/<slug:slug>', actualizarCajas, name='actualizar_cajas'),
    path('eliminar_cajas/', eliminar_Cajas, name='eliminar_cajas'),

    # URLs para ver las cajas
    path('tipo_operacion', tipo_operacion, name='tipo_operacion'),
    path('actualizar_tipo_operacion/<slug:slug>', actualizarTipo_operacion, name='actualizar_tipo_operacion'),
    path('eliminar_tipo_operacion/', eliminar_Tipo_operacion, name='eliminar_tipo_operacion'),

    # URLs para ver las denominaciones
    path('denominacion', denominacion, name='denominacion'),
    path('actualizar_denominacion/<slug:slug>', actualizarDenominacion, name='actualizar_denominacion'),
    path('eliminar_denominacion/', eliminar_Denominacion, name='eliminar_denominacion'),

    # URLs para ver el uso de cajas
    path('registro_cajas', registro_cajas, name='registro_cajas'),
    path('actualizar_registro_cajas/<slug:slug>', actualizarRegistro_cajas, name='actualizar_registro_cajas'),
    path('eliminar_registro_cajas', eliminar_Registro_cajas, name='eliminar_registro_cajas'),

    # URLs para ver el manejo de los Alimentos
    path('alimentos', alimentos, name='alimentos'),
    path('actualizar_alimentos/<slug:slug>', actualizarAlimentos, name='actualizar_alimentos'),
    path('eliminar_alimentos/', eliminar_Alimentos, name='eliminar_alimentos'),

    # URLs para ver el manejo de los Alimentos
    path('combos', combos, name='combos'),
    path('actualizar_combos/<slug:slug>', actualizarCombos, name='actualizar_combos'),
    path('eliminar_combos/', eliminar_Combos, name='eliminar_combos'),

    # URLs para ver el manejo de los Alimentos
    path('productos', productos, name='productos'),
    path('actualizar_productos/<slug:slug>', actualizarProductos, name='actualizar_productos'),
    path('eliminar_productos/', eliminar_Producto, name='eliminar_productos'),

    # URLs para ver el manejo de las promociones
    path('promociones', promociones, name='promos'),
    path('actualizar_promociones/<slug:slug>', actualizarPromociones, name='actualizar_promos'),
    path('eliminar_promociones/', eliminar_Promocion, name='eliminar_promos'),

    # URLs para ver el manejo de las promociones
    path('proveedores', proveedores, name='proveedores'),
    path('actualizar_proveedores/<slug:slug>', actualizarProveedores, name='actualizar_proveedores'),
    path('eliminar_proveedores/', eliminar_Proveedores, name='eliminar_proveedores'),

]

punto_de_venta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admino/', admin.site.urls),
    path('', include('apps.MainApp.urls')),
    path('cajeros/', include('apps.CajerosApp.urls')),
    path('meseros/', include('apps.MeserosApp.urls')),
    path('admin/', include('apps.AdminsApp.urls')),
]

templates/Admins/Alimentos/alimentos_dir/actualizaAlimentos.html
{% extends 'Admins/navbar.html' %}

    {% block title %}Actualizar{% endblock %}

{% block body %}

    <div class="container">
    <div class="col-md-6">
        <form method="post">
            {% csrf_token %}

            {{ form }}

            <div class="row justify-content-md-center mt-5">
                <button type="submit" class="btn btn-success">Actualizar</button>
            </div>
        </form>
    </div>
    </div>

{% endblock %}

templates/Admins/Alimentos/alimentos_dir/alimentos.html
{% extends 'Admins/navbar.html' %}
{% load static %}


{% block title %} Insumos {% endblock %}

{% block css %}
    <style>
        #btnsubmit {
            background: url(../../../../static/recursos/img/trash.png) no-repeat;
            width: 28px;
            height: 28px;
            border: none;
        }
    </style>
{% endblock %}

{% block body %}

    <div class="container">

    <div class="row justify-content-md-center">
            <div class=" mt-4 mb-5">
                {% for message in messages %}
                    {% if message.tags == "error" %}
                        <p class="bg-danger" style="font-size: 24px; color: white;">{{ message }}</p>
                    {% else %}
                        <p class="bg-success" style="font-size: 24px; color: white;">{{ message }}</p>
                    {% endif %}

                {% endfor %}
            </div>
        </div>


        <div class="row justify-content-center mt-5">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#nuevousuarioModal">
                Agregar Alimento
            </button>
        </div>


        {% if query %}

            <div class="row mt-5">
                <table class="table">
                    <thead class="thead-light">
                    <tr>
                        <th scope="col">Nombre</th>
                        <th scope="col">Categoria</th>
                        <th scope="col">Descripcion</th>
                        <th scope="col">Precio</th>
                        <th scope="col">Opciones</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for i in query %}
                        <tr>
                            <td>{{ i.nombre }}</td>
                            <td>{{ i.descripcion }}</td>
                            <td>{{ i.categoria }}</td>
                            <td>{{ i.precio }}</td>

                            <td>
                                <div class="row">
                                    <div class="col">
                                        <a href="{% url 'admin:actualizar_alimentos' i.slug %}"> <img src="{% static 'recursos/img/actualizar.png' %}"></a>
                                    </div>

                                    <div class="col">
                                        <form method="post" action="{% url 'admin:eliminar_alimentos' %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="slug" value="{{ i.slug }}">
                                        <button type="submit" id="btnsubmit"></button>
                                    </form>

                                    </div>
                                </div>
                            </td>

                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

        {% else %}

            <div class="row justify-content-md-center">
                <div class="mt-4">
                    <h3>No hay alimentos</h3>
                </div>
            </div>

        {% endif %}

    </div>



    <!-- Modal -->
    <div class="modal fade" id="nuevousuarioModal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Agregar Alimentos</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="post" id="form">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-success" id="btnForm">
                        Registrar
                    </button>
                </div>
            </div>
        </div>
    </div>


    {% block script %}

        <script>
            document.getElementById('btnForm').addEventListener('click', function () {
                document.getElementById('form').submit()
            })
        </script>
        <script src="{% static 'js/empleados/empleados.js' %}"></script>



    {% endblock %}

{% endblock %}